# Real-world Data Wrangling

In this project, you will apply the skills you acquired in the course to gather and wrangle real-world data with two datasets of your choice.

You will retrieve and extract the data, assess the data programmatically and visually, accross elements of data quality and structure, and implement a cleaning strategy for the data. You will then store the updated data into your selected database/data store, combine the data, and answer a research question with the datasets.

Throughout the process, you are expected to:

1. Explain your decisions towards methods used for gathering, assessing, cleaning, storing, and answering the research question
2. Write code comments so your code is more readable

## 1. Gather data

In this section, you will extract data using two different data gathering methods and combine the data. Use at least two different types of data-gathering methods.

### **1.1.** Problem Statement
In 2-4 sentences, explain the kind of problem you want to look at and the datasets you will be wrangling for this project.

In this project exercise I will use related data sets related to Coronavirus (Covid-19) Data for analysis. I will use four datasets with:<br>
- Data set with files ".csv": us_covid19_daily.csv.<br>
    Link to download file: https://www.kaggle.com/code/sudalairajkumar/covid-19-analysis-of-usa/input?select=us_covid19_daily.csv<br>
- Data set with ".zip" file: archive.zip.<br>
    Link to download file: https://www.kaggle.com/datasets/gpreda/covid-world-vaccination-progress/download?datasetVersionNumber=249<br>
Is it possible to combine these data sets into one dataset<br>ta set?

### **1.2.** Gather at least two datasets using two different data gathering methods

List of data gathering methods:

- Download data manually
- Programmatically downloading files
- Gather data by accessing APIs
- Gather and extract data from HTML files using BeautifulSoup
- Extract data from a SQL database

Each dataset must have at least two variables, and have greater than 500 data samples within each dataset.

For each dataset, briefly describe why you picked the dataset and the gathering method (2-3 full sentences), including the names and significance of the variables in the dataset. Show your work (e.g., if using an API to download the data, please include a snippet of your code). 

Load the dataset programmtically into this notebook.

In [16]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import matplotlib as mpl
import zipfile
import requests
import os
import seaborn as sb
%matplotlib inline

#### Dataset 1: 
File name        : us_covid19_daily.csv.<br>
Type             : CSV File.<br>
Objective        : Objective of this notebook is to explore the COVID-19 data of US and its states.<br>
Method           : The data was gathered using the "Download data manually" method from "www.kaggle.com" source.<br>
About this file  : Daily level information of COVID-19 tests in US.<br>
Dataset variables:<br>
*   *date    : Date of observation.*
*   *state   : Number of states with covid-19 cases.*
*   *positive: Number of tests with positive result.*
*   *negative: Number of tests with negative result.*
*   *pending : Number of tests with positive & negative result.*
*   *hospitalizedCurrently: Number of tests with pending result.*
*   *hospitalizedCumulative: Number of hospitalized cases.*
*   *inIcuCurrently: Number of death cases.*
*   *inIcuCumulative: Total number of test taken.*
*   *onVentilatorCurrently: Date checked.*
*   *onVentilatorCumulative: Total number of tests with results.*
*   *recovered: Number of new deaths in last one day.*
*   *hash: Number of new hospitalized cases in last one day.*
*   *dateChecked: Number of new negative test results in last one day.*
*   *death: Number of new positive test results in last one day.*
*   *hospitalized: Number of new total test results in last one day.*
*   *fips  : Codes for States and Counties.*
*   *total, totalTestResults, posNeg, fips, deathIncrease, hospitalizedIncrease, negativeIncrease, positiveIncrease, totalTestResultsIncrease* and probable.N*

In [2]:
#FILL IN 1st data gathering and loading method
df_us_covid19 = pd.read_csv('us_covid19_daily.csv')
df_us_covid19

,date,states,positive,negative,pending,hospitalizedCurrently,hospitalizedCumulative,inIcuCurrently,inIcuCumulative,onVentilatorCurrently,...,hospitalized,total,totalTestResults,posNeg,fips,deathIncrease,hospitalizedIncrease,negativeIncrease,positiveIncrease,totalTestResultsIncrease
0,20200601,56,1799761,15540921.0,3455.0,33237.0,212704.0,7620.0,8485.0,3661.0,...,212704.0,17344137,17340682,17340682,NaN,469.0,2621.0,387600.0,16191.0,403791.0
1,20200531,56,1783570,15153321.0,3270.0,33840.0,210083.0,7623.0,8445.0,3669.0,...,210083.0,16940161,16936891,16936891,NaN,656.0,949.0,383661.0,22545.0,406206.0
2,20200530,56,1761025,14769660.0,1668.0,34650.0,209134.0,7956.0,8305.0,4004.0,...,209134.0,16532353,16530685,16530685,NaN,989.0,1440.0,406716.0,24454.0,431170.0
3,20200529,56,1736571,14362944.0,2978.0,35871.0,207694.0,8175.0,8235.0,4032.0,...,207694.0,16102493,16099515,16099515,NaN,1186.0,1720.0,468342.0,23934.0,492276.0
4,20200528,56,1712637,13894602.0,1906.0,36967.0,205974.0,8389.0,8109.0,4080.0,...,205974.0,15609145,15607239,15607239,NaN,1353.0,2500.0,391751.0,23007.0,414758.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
127,20200126,1,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,1,1,1,NaN,0.0,0.0,0.0,0.0,0.0
128,20200125,1,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,1,1,1,NaN,0.0,0.0,0.0,0.0,0.0
129,20200124,1,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,1,1,1,NaN,0.0,0.0,0.0,0.0,0.0
130,20200123,1,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,1,1,1,NaN,0.0,0.0,0.0,0.0,0.0
131,20200122,1,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,1,1,1,NaN,NaN,NaN,NaN,NaN,NaN

#### Dataset 2: 
File name        : usa_county_wise.csv.<br>
Type             : CSV File.<br>
Objective        : Vaccination rate affects the number of cases per day.<br>
Method           : The data was gathered using the "Programmatically downloading files" method from "www.kaggle.com" source.<br>
About this file  : Country level vaccination data.<br>
Dataset variables:

*   *Country- this is the country for which the vaccination information is provided;*
*   *Country ISO Code - ISO code for the country;*
*   *Date - date for the data entry; for some of the dates we have only the daily vaccinations, for others, only the (cumulative) total;*
*   *Total number of vaccinations - this is the absolute number of total immunizations in the country;*
*   *Total number of people vaccinated - a person, depending on the immunization scheme, will receive one or more (typically 2) vaccines; at a certain moment, the number of vaccination might be larger than the number of people;*
*   *Total number of people fully vaccinated - this is the number of people that received the entire set of immunization according to the immunization scheme (typically 2); at a certain moment in time, there might be a certain number of people that received one vaccine and another number (smaller) of people that received all vaccines in the scheme;hDaily vaccinations (raw) - for a certain data entry, the number of vaccination for that date/country;*
*   *Daily vaccinations - for a certain data entry, the number of vaccination for that date/country;*
*   *Total vaccinations per hundred - ratio (in percent) between vaccination number and total population up to the date in the country;*
*   *Total number of people vaccinated per hundred - ratio (in percent) between population immunized and total population up to the date in the country;*
*   *Total number of people fully vaccinated per hundred - ratio (in percent) between population fully immunized and total population up to the date in the country;*
*   *Number of vaccinations per day - number of daily vaccination for that day and country;*
*   *Daily vaccinations per million - ratio (in ppm) between vaccination number and total population for the current date in the country;*
*   *Vaccines used in the country - total number of vaccines used in the country (up to date);*
*   *Source name - source of the information (national authority, international organization, local al organization etc*.*   *);
Source website - website of the source of informat*ion;e country;

In [31]:
#FILL IN 1st data gathering and loading method
data_country_vaccinations = requests.get("https://www.kaggle.com/datasets/gpreda/covid-world-vaccination-progress/download?datasetVersionNumber=249",stream=True)
data_country_vaccinations

In [32]:
data_country_vaccinations.raise_for_status()

In [33]:
data_country_vaccinations.url

'https://www.kaggle.com/account/login?titleType=dataset-downloads&showDatasetDownloadSkip=False&messageId=datasetsWelcome&returnUrl=%2Fdatasets%2Fgpreda%2Fcovid-world-vaccination-progress%2Fversions%2F249%3Fresource%3Ddownload'

In [27]:
data_country_vaccinations.headers

{'Content-Type': 'text/html; charset=utf-8', 'Date': 'Thu, 18 Apr 2024 14:56:44 GMT', 'Cache-Control': 'no-cache, no-store', 'Content-Encoding': 'br', 'Pragma': 'no-cache', 'Set-Cookie': 'CSRF-TOKEN=CfDJ8CYusWan8yNKiDQcrMXOtQEn-xUn7AaYL8WVPpqulOuRqykUG7Se40IfVDuRTBWcdErYWo9Y1-pqNsBDXfGUVIm_JXWy1RECvWKb8j-XAg; path=/; secure; samesite=lax; httponly, XSRF-TOKEN=CfDJ8CYusWan8yNKiDQcrMXOtQGsd3_y7SoalJJrojmpDiKySR7GOZtd3A-evqrthbYL6OgqDQE6dXhS3gsR4-TfJccFu0kjTC656JzHkpyuZPSDhg; path=/; secure; samesite=lax, CLIENT-TOKEN=eyJhbGciOiJub25lIiwidHlwIjoiSldUIn0.eyJpc3MiOiJrYWdnbGUiLCJhdWQiOiJjbGllbnQiLCJzdWIiOm51bGwsIm5idCI6IjIwMjQtMDQtMThUMTQ6NTY6NDQuNDQ5MDU3MloiLCJpYXQiOiIyMDI0LTA0LTE4VDE0OjU2OjQ0LjQ0OTA1NzJaIiwianRpIjoiOTZmNjJkNjMtMmMyYy00MGUzLWJmYjEtM2RiNzFiNTdlNTBjIiwiZXhwIjoiMjAyNC0wNS0xOFQxNDo1Njo0NC40NDkwNTcyWiIsImFub24iOnRydWUsImZmIjpbIktlcm5lbHNHaXRodWJTeW5jIiwiSW1wb3J0S2VybmVsc0Zyb21Db2xhYiIsIktlcm5lbHNFeHBvcnRNZXRhZGF0YSIsIktlcm5lbHNGaXJlYmFzZUxvbmdQb2xsaW5nIiwiQ29tbXVuaXR5TG93ZXJIZWFkZXJTaXplcyIsIkFsbG93Rm9ydW1BdHRhY2htZW50cyIsIkZyb250ZW5kRXJyb3JSZXBvcnRpbmciLCJEYXRhc2V0c01hbmFnZWRGb2N1c09uT3BlbiIsIkNoYW5nZURhdGFzZXRPd25lcnNoaXBUb09yZyIsIkV4cG9ydERhdGFzZXRBc0Nyb2lzc2FudCIsIktNVXNlclByb2ZpbGUiLCJNb2RlbHNDYWNoZWRUYWdTZXJ2aWNlRW5hYmxlZCIsIk9yZ2FuaXphdGlvbnNWMiIsIkRpc2N1c3Npb25zUmVhY3Rpb25zIiwiRGF0YXNldFVwbG9hZGVyRHVwbGljYXRlRGV0ZWN0aW9uIiwiTW9kZWxzQWxsb3dTZXRWaXNpYmlsaXR5IiwiRGF0YXNldHNNZXRhZGF0YVN1Z2dlc3Rpb25zIiwiS2VybmVsc09wZW5Ob3RlYm9va0luQ29sYWIiLCJNb2RlbHNCb29rbWFya2luZyIsIktlcm5lbHNEZWxldGVLZXJuZWxGcm9tRWRpdG9yIiwiTW9kZWxzTGFuZGluZ1BhZ2VDb21tdW5pdHlTZWN0aW9uRW5hYmxlZCIsIkxpY2Vuc2VVc2VTZWNvbmRSZXZpc2lvbiJdLCJmZmQiOnsiS2VybmVsRWRpdG9yQXV0b3NhdmVUaHJvdHRsZU1zIjoiMzAwMDAiLCJFbWVyZ2VuY3lBbGVydEJhbm5lciI6Int9IiwiQ2xpZW50UnBjUmF0ZUxpbWl0UXBzIjoiNDAiLCJDbGllbnRScGNSYXRlTGltaXRRcG0iOiI1MDAiLCJGZWF0dXJlZENvbW11bml0eUNvbXBldGl0aW9ucyI6IjYwMDk1LDU0MDAwLDU3MTYzIiwiQWRkRmVhdHVyZUZsYWdzVG9QYWdlTG9hZFRhZyI6ImRpc2FibGVkIiwiTW9kZWxJZHNBbGxvd0luZmVyZW5jZSI6IjMzMDEsMzUzMyIsIk1vZGVsSW5mZXJlbmNlUGFyYW1ldGVycyI6InsgXCJtYXhfdG9rZW5zXCI6IDEyOCwgXCJ0ZW1wZXJhdHVyZVwiOiAwLjQsIFwidG9wX2tcIjogNSB9IiwiU2ltQ29tcGV0aXRpb25JZHNUb0lnbm9yZVVwbG9hZExpbWl0IjoiNjAyNDMsNjEyNTAiLCJDb21wZXRpdGlvbk1ldHJpY1RpbWVvdXRNaW51dGVzIjoiMzAiLCJUZkh1YkthZ2dsZUFubm91bmNlbWVudFVybCI6Ii9kaXNjdXNzaW9ucy9wcm9kdWN0LWZlZWRiYWNrLzQ0ODQyNSJ9LCJwaWQiOiJrYWdnbGUtMTYxNjA3Iiwic3ZjIjoid2ViLWZlIiwic2RhayI6IkFJemFTeUE0ZU5xVWRSUnNrSnNDWldWei1xTDY1NVhhNUpFTXJlRSIsImJsZCI6ImExYTEwYzVjMDE1Y2ZmMTM2ZTU2MmQ0ZWY2Mjg0OWZlZTEyNDg5NzcifQ.; path=/; secure; samesite=lax', 'Vary': 'Accept-Encoding', 'Turbolinks-Location': 'https://www.kaggle.com/account/login?titleType=dataset-downloads&showDatasetDownloadSkip=False&messageId=datasetsWelcome&returnUrl=%2Fdatasets%2Fgpreda%2Fcovid-world-vaccination-progress%2Fversions%2F249%3Fresource%3Ddownload', 'X-Frame-Options': 'SAMEORIGIN', 'Strict-Transport-Security': 'max-age=63072000; includeSubDomains; preload', 'Content-Security-Policy': "object-src 'none'; script-src 'nonce-HpSHkI4p+nMc/voIGDfG1g==' 'report-sample' 'unsafe-inline' 'unsafe-eval' 'strict-dynamic' https: http:; base-uri 'none'; report-uri https://csp.withgoogle.com/csp/kaggle/20201130; frame-src 'self' https://www.kaggleusercontent.com https://www.youtube.com/embed/ https://polygraph-cool.github.io https://www.google.com/recaptcha/ https://www.docdroid.com https://www.docdroid.net https://kaggle-static.storage.googleapis.com https://kkb-production.jupyter-proxy.kaggle.net https://kkb-production.firebaseapp.com https://kaggle-metastore.firebaseapp.com https://apis.google.com https://content-sheets.googleapis.com/ https://accounts.google.com/ https://storage.googleapis.com https://docs.google.com https://drive.google.com https://calendar.google.com/;", 'X-Content-Type-Options': 'nosniff', 'Referrer-Policy': 'strict-origin-when-cross-origin', 'Via': '1.1 google', 'Alt-Svc': 'h3=":443"; ma=2592000,h3-29=":443"; ma=2592000', 'Transfer-Encoding': 'chunked'}

In [35]:
#unzip the zip file in read mode using a context manager
with zipfile.ZipFile("archive.zip","r") as zip_ref:
    zip_ref.extractall("")

#os.remove("archive.zip")

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

data = pd.read_csv("/kaggle/input/covid-world-vaccination-progress/country_vaccinations.csv")
data.head()

In [48]:
#FILL IN 2nd data gathering and loading method
data_vaccinations = pd.read_csv('us_covid19_daily.csv')
data_vaccinations

,date,states,positive,negative,pending,hospitalizedCurrently,hospitalizedCumulative,inIcuCurrently,inIcuCumulative,onVentilatorCurrently,...,hospitalized,total,totalTestResults,posNeg,fips,deathIncrease,hospitalizedIncrease,negativeIncrease,positiveIncrease,totalTestResultsIncrease
0,20200601,56,1799761,15540921.0,3455.0,33237.0,212704.0,7620.0,8485.0,3661.0,...,212704.0,17344137,17340682,17340682,NaN,469.0,2621.0,387600.0,16191.0,403791.0
1,20200531,56,1783570,15153321.0,3270.0,33840.0,210083.0,7623.0,8445.0,3669.0,...,210083.0,16940161,16936891,16936891,NaN,656.0,949.0,383661.0,22545.0,406206.0
2,20200530,56,1761025,14769660.0,1668.0,34650.0,209134.0,7956.0,8305.0,4004.0,...,209134.0,16532353,16530685,16530685,NaN,989.0,1440.0,406716.0,24454.0,431170.0
3,20200529,56,1736571,14362944.0,2978.0,35871.0,207694.0,8175.0,8235.0,4032.0,...,207694.0,16102493,16099515,16099515,NaN,1186.0,1720.0,468342.0,23934.0,492276.0
4,20200528,56,1712637,13894602.0,1906.0,36967.0,205974.0,8389.0,8109.0,4080.0,...,205974.0,15609145,15607239,15607239,NaN,1353.0,2500.0,391751.0,23007.0,414758.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
127,20200126,1,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,1,1,1,NaN,0.0,0.0,0.0,0.0,0.0
128,20200125,1,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,1,1,1,NaN,0.0,0.0,0.0,0.0,0.0
129,20200124,1,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,1,1,1,NaN,0.0,0.0,0.0,0.0,0.0
130,20200123,1,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,1,1,1,NaN,0.0,0.0,0.0,0.0,0.0
131,20200122,1,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,1,1,1,NaN,NaN,NaN,NaN,NaN,NaN

Optional data storing step: You may save your raw dataset files to the local data store before moving to the next step.

In [49]:
#Optional: store the raw data in your local data store
df_covid19 = df_us_covid19.copy()
df_covid19

,date,states,positive,negative,pending,hospitalizedCurrently,hospitalizedCumulative,inIcuCurrently,inIcuCumulative,onVentilatorCurrently,...,hospitalized,total,totalTestResults,posNeg,fips,deathIncrease,hospitalizedIncrease,negativeIncrease,positiveIncrease,totalTestResultsIncrease
0,20200601,56,1799761,15540921.0,3455.0,33237.0,212704.0,7620.0,8485.0,3661.0,...,212704.0,17344137,17340682,17340682,NaN,469.0,2621.0,387600.0,16191.0,403791.0
1,20200531,56,1783570,15153321.0,3270.0,33840.0,210083.0,7623.0,8445.0,3669.0,...,210083.0,16940161,16936891,16936891,NaN,656.0,949.0,383661.0,22545.0,406206.0
2,20200530,56,1761025,14769660.0,1668.0,34650.0,209134.0,7956.0,8305.0,4004.0,...,209134.0,16532353,16530685,16530685,NaN,989.0,1440.0,406716.0,24454.0,431170.0
3,20200529,56,1736571,14362944.0,2978.0,35871.0,207694.0,8175.0,8235.0,4032.0,...,207694.0,16102493,16099515,16099515,NaN,1186.0,1720.0,468342.0,23934.0,492276.0
4,20200528,56,1712637,13894602.0,1906.0,36967.0,205974.0,8389.0,8109.0,4080.0,...,205974.0,15609145,15607239,15607239,NaN,1353.0,2500.0,391751.0,23007.0,414758.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
127,20200126,1,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,1,1,1,NaN,0.0,0.0,0.0,0.0,0.0
128,20200125,1,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,1,1,1,NaN,0.0,0.0,0.0,0.0,0.0
129,20200124,1,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,1,1,1,NaN,0.0,0.0,0.0,0.0,0.0
130,20200123,1,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,1,1,1,NaN,0.0,0.0,0.0,0.0,0.0
131,20200122,1,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,1,1,1,NaN,NaN,NaN,NaN,NaN,NaN

In [51]:
df_vaccinations = data_vaccinations.copy()
df_vaccinations

,date,states,positive,negative,pending,hospitalizedCurrently,hospitalizedCumulative,inIcuCurrently,inIcuCumulative,onVentilatorCurrently,...,hospitalized,total,totalTestResults,posNeg,fips,deathIncrease,hospitalizedIncrease,negativeIncrease,positiveIncrease,totalTestResultsIncrease
0,20200601,56,1799761,15540921.0,3455.0,33237.0,212704.0,7620.0,8485.0,3661.0,...,212704.0,17344137,17340682,17340682,NaN,469.0,2621.0,387600.0,16191.0,403791.0
1,20200531,56,1783570,15153321.0,3270.0,33840.0,210083.0,7623.0,8445.0,3669.0,...,210083.0,16940161,16936891,16936891,NaN,656.0,949.0,383661.0,22545.0,406206.0
2,20200530,56,1761025,14769660.0,1668.0,34650.0,209134.0,7956.0,8305.0,4004.0,...,209134.0,16532353,16530685,16530685,NaN,989.0,1440.0,406716.0,24454.0,431170.0
3,20200529,56,1736571,14362944.0,2978.0,35871.0,207694.0,8175.0,8235.0,4032.0,...,207694.0,16102493,16099515,16099515,NaN,1186.0,1720.0,468342.0,23934.0,492276.0
4,20200528,56,1712637,13894602.0,1906.0,36967.0,205974.0,8389.0,8109.0,4080.0,...,205974.0,15609145,15607239,15607239,NaN,1353.0,2500.0,391751.0,23007.0,414758.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
127,20200126,1,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,1,1,1,NaN,0.0,0.0,0.0,0.0,0.0
128,20200125,1,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,1,1,1,NaN,0.0,0.0,0.0,0.0,0.0
129,20200124,1,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,1,1,1,NaN,0.0,0.0,0.0,0.0,0.0
130,20200123,1,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,1,1,1,NaN,0.0,0.0,0.0,0.0,0.0
131,20200122,1,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,1,1,1,NaN,NaN,NaN,NaN,NaN,NaN

## 2. Assess data

Assess the data according to data quality and tidiness metrics using the report below.

List **two** data quality issues and **two** tidiness issues. Assess each data issue visually **and** programmatically, then briefly describe the issue you find.  **Make sure you include justifications for the methods you use for the assessment.**

### Quality Issue 1:

In [ ]:
#FILL IN - Inspecting the dataframe visually

In [ ]:
#FILL IN - Inspecting the dataframe programmatically

Issue and justification: *FILL IN*

### Quality Issue 2:

In [ ]:
#FILL IN - Inspecting the dataframe visually

In [ ]:
#FILL IN - Inspecting the dataframe programmatically

Issue and justification: *FILL IN*

### Tidiness Issue 1:

In [ ]:
#FILL IN - Inspecting the dataframe visually

In [ ]:
#FILL IN - Inspecting the dataframe programmatically

Issue and justification: *FILL IN*

### Tidiness Issue 2:

In [ ]:
#FILL IN - Inspecting the dataframe visually

In [ ]:
#FILL IN - Inspecting the dataframe programmatically

Issue and justification: *FILL IN*

## 3. Clean data
Clean the data to solve the 4 issues corresponding to data quality and tidiness found in the assessing step. **Make sure you include justifications for your cleaning decisions.**

After the cleaning for each issue, please use **either** the visually or programatical method to validate the cleaning was succesful.

At this stage, you are also expected to remove variables that are unnecessary for your analysis and combine your datasets. Depending on your datasets, you may choose to perform variable combination and elimination before or after the cleaning stage. Your dataset must have **at least** 4 variables after combining the data.

In [ ]:
# FILL IN - Make copies of the datasets to ensure the raw dataframes 
# are not impacted

### **Quality Issue 1: FILL IN**

In [ ]:
# FILL IN - Apply the cleaning strategy

In [ ]:
# FILL IN - Validate the cleaning was successful

Justification: *FILL IN*

### **Quality Issue 2: FILL IN**

In [ ]:
#FILL IN - Apply the cleaning strategy

In [ ]:
#FILL IN - Validate the cleaning was successful

Justification: *FILL IN*

### **Tidiness Issue 1: FILL IN**

In [ ]:
#FILL IN - Apply the cleaning strategy

In [ ]:
#FILL IN - Validate the cleaning was successful

Justification: *FILL IN*

### **Tidiness Issue 2: FILL IN**

In [1]:
#FILL IN - Apply the cleaning strategy

In [2]:
#FILL IN - Validate the cleaning was successful

Justification: *FILL IN*

### **Remove unnecessary variables and combine datasets**

Depending on the datasets, you can also peform the combination before the cleaning steps.

In [ ]:
#FILL IN - Remove unnecessary variables and combine datasets

## 4. Update your data store
Update your local database/data store with the cleaned data, following best practices for storing your cleaned data:

- Must maintain different instances / versions of data (raw and cleaned data)
- Must name the dataset files informatively
- Ensure both the raw and cleaned data is saved to your database/data store

In [ ]:
#FILL IN - saving data

## 5. Answer the research question

### **5.1:** Define and answer the research question 
Going back to the problem statement in step 1, use the cleaned data to answer the question you raised. Produce **at least** two visualizations using the cleaned data and explain how they help you answer the question.

*Research question:* FILL IN from answer to Step 1

In [ ]:
#Visual 1 - FILL IN

*Answer to research question:* FILL IN

In [ ]:
#Visual 2 - FILL IN

*Answer to research question:* FILL IN

### **5.2:** Reflection
In 2-4 sentences, if you had more time to complete the project, what actions would you take? For example, which data quality and structural issues would you look into further, and what research questions would you further explore?

*Answer:* FILL IN